### ISSUE TITLE
Commas not escaped in cvlist

### ISSUE THREAD

**Issue by fozy81** [schochastics/sidebar-cv#2]
Hi, thank you for these great CV templates. When adding 'details' to the tribble table to outline contributions, any commas in the description create line breaks in the output. 

For example "sampling, and reporting" becomes:

![image](https://github.com/user-attachments/assets/07935836-c832-453e-a487-31fdc476bcbd)

Is there a way to allow commas in the description without creating line breaks? 

It looks to be `foreach` latex command which treats each comma separator as a separate item. I can't find an easy way around this. Many Thanks for any help.

**Comment by schochastics** [comment]
@fozy81 writing "sampling{,} and reporting" should do the trick

**Comment by fozy81** [comment]
Many thanks, knew there must be a quick fix!
